### PR TITLE
Update final copies of txt and html for 13 publication

### PR DESCRIPTION
**Pull request by johngray-dev**
Final version of -13 for this repository.

### CODE REVIEW

**Comment by janklaussner** [comment]
As written in the e-Mail I would remove line 181 "TODO:  Dive through Stravos?" or rephrase it

**Comment by janklaussner** [comment]
review done, one comment above and one [issue](https://github.com/EntrustCorporation/draft-ounsworth-composite-sigs/issues/143) for later

**Comment by johngray-dev** [comment]
Thanks,  I will remove that line...   I noticed it as well and agree it should be removed.

**Comment by johngray-dev** [comment]
Merging pull request - Jan reviewed, opened one issue that will be fixed after.

**Pull request closed without merging**
